export const adjective: Adjective[] = [
	["too sweaty", "niffyjiffy"],
	["too small", "niffyjiffy"],
	["in my eyes", "niffyjiffy"],
	["tired", "niffyjiffy"],
	["too bright", "niffyjiffy"],
	["in pain", "niffyjiffy"],

	["too big", "Taerk"],
	["too loud", "Taerk"],
	["too annoying", "Taerk"],
	["broken", "Taerk"],
	["overpowered", "Taerk"],
	["biased", "Taerk"],
	["modded", "Taerk"],
	["on fire", "Taerk"],
	["ugly", "Taerk"],
	["too salty", "Taerk"],
	["not subscribed", "Taerk"],
	["too old", "Taerk"],
	["against me", "Taerk"],

	["too slow", "/u/Abraman1"],
	["too laggy", "/u/DrankeyKrang"],
	["too dull", "/u/DrankeyKrang"],
	["itchy", "/u/shadowpikachu"],
	["too cold", "/u/p0rtugalvii"],
	["too warm", "/u/p0rtugalvii"],
	["too hard to see", "/u/Slyphoria"],
	["too advanced", "/u/DrankeyKrang"],
	["outdated", "/u/DrankeyKrang"],
	["too casual", "/u/DrankeyKrang"],
	["not casual enough", "/u/DrankeyKrang"],
	["scratched up", "/u/DeadLineClock"],
	["not HD", "/u/Mitsjol"],
	["too glitchy", "/u/DrankeyKrang"],
	["too unstable", "/u/DrankeyKrang"],
	["too johnny", "/u/DrankeyKrang"],
	["butthurt", "/u/shadowpikachu"],
	["THE TOURNAMENT!", "/u/DeadLineClock"],
	["third-party", "/u/Mitsjol"],
	["sweaty", "/u/Mitsjol"],
	["really feeling it!", "/u/PhoenixBurning"],
	["not paying attention", "/u/PyrokidSosa"],
	["distracted by that girl", "/u/Her0_0f_time"],
	["being so loud", "/u/GSRaposo"],
	["nerfed again", "/u/Gandesa"],

	["in my eyes", "Poyoarya"],
	["broken", "Poyoarya"],
	["laggy", "Poyoarya"],
	["hacked", "Poyoarya"],
	["too loud", "Poyoarya"],
	["uncomfortable", "Poyoarya"],
	["OP", "Poyoarya"],
	["fraudulent", "Poyoarya"],
	["too bright", "Poyoarya"],
	["nerfed", "Poyoarya"],
	["garbage", "Poyoarya"],
	["not good enough", "Poyoarya"],
	["really annoying", "Poyoarya"],
	["a big gimmick", "Poyoarya"],
	["kinda sweaty", "Poyoarya"],
	["Reggie Fils-Aim&eacute;", "Poyoarya"],
	["ethically superior to me", "Poyoarya"],
	["incapable of melting steel beams", "Poyoarya"],
	["too attractive", "Poyoarya"],
	["too fast", "Poyoarya"],
	["bad and should feel bad", "Poyoarya"],
	["low on batteries", "Poyoarya"],
	["cold", "Poyoarya"],
	["sticky", "Poyoarya"],
	["not fair", "Poyoarya"],
	["sober", "Poyoarya"],
	["unnecessarily rude", "Poyoarya"],
	["upside-down", "Poyoarya"],
	["way better than my character", "Poyoarya"],
	["terrible for my character", "Poyoarya"],
	["too hard to reach", "Poyoarya"],
	["really hard to remember", "Poyoarya"],
	["not listening to me", "Poyoarya"],

	["not a real person", "Copilot"],
	["horny", 'wsbc'],
	["naked", "wsbc"],
	["fat", "wsbc"],
	["high", "wsbc"],
	["so fucked", "wsbc"],
	["a fucking architect", 'Clark'],
	["my wife", "wsbc"],
	["racist", "wsbc"],
	["pure, unadulterated jank", 'Google'],
	["smelly", "wsbc"],
	["not a natural formation", "notamacuser"],
	["not old enough", 'wsbc'],
	["the Senate", 'Palpatine'],
	["a shill", 'wsbc'],
	["streaming", 'wsbc'],
	["in The Files", "wsbc"],
	['<span style="font-variant:small-caps">ludicrously</span> gay', "wsbc"],
	["illegal, you know", "wsbc"],
	["poor", "wsbc"],
	["going vertical", 'Vert Wheeler'],
	["mad because I broke the glass", "Clark"],
];
