export const johns_connable: ConnableVerb[] = [
	["counter-pick", "the stage", "Taerk"],
	["counter-pick", "the character", "Taerk"],
	["self-destruct", "", "Taerk"],
	["hack", "", "Taerk"],
	["cheat", "", "Taerk"],
	["listen", "to the wrong song", "Taerk"],
	["mess", "with the setup", "Taerk"],
	["use", "the wrong tag", "Taerk"],
	["lose", "on purpose", "Taerk"],
	["use", "rumble", "Taerk"],
	["team", "up on me", "Taerk"],

	["kill", "me", "/u/Mitsjol"],
	["make", "me sleepy", "/u/RoflPost"],
	["use", "illegal tactics", "/u/DrankeyKrang"],
	["use", "banned characters", "/u/DrankeyKrang"],
	["use", "glitches", "/u/DrankeyKrang"],
	["only play", "to win", "/u/DrankeyKrang"],
	["explode", "", "/u/Her0_0f_time"],
	["slip", "", "/u/ProjectMFeeni-ngNigga"],
	["stare", "at me", "/u/2m2m_NoClown"],
	["stare", "at you", "/u/2m2m_NoClown"],
	["nudge", "my R-cancelling knee", "/u/Erotaku12943"],
	["use", "gimmicky custom moves", "/u/DrankeyKrang"],
	["throw", "something at me", "/u/DeadLineClock"],
	["call", "me names", "/u/DeadLineClock"],
	["get", "too much sleep", "/u/Her0_0f_time"],
	["murder", "the commentator", "/u/DeadLineClock"],
	["tell", "me it would work", "/u/NormalNavi"],
	["save", "you", "/u/Mitsjol"],
	["want", "to make a gfycat", "/u/Her0_0f_time"],
	["mess", "up my L-cancels", "/u/Erotaku12943"],
	["call", "me", "/u/Mitsjol"],
	["steal", "my main", "/u/404House"],
	["spam", "the C-stick", "/u/KindaFunnyUsername"],
	["tell", "ridiculous johns", "/u/Her0_0f_time"],

	["walk", "in front of the screen", "Poyoarya"],
	["tangle", "my controller cable", "Poyoarya"],
	["sleep", "", "Poyoarya"],
	["taunt", "", "Poyoarya"],
	["cheat", "", "Poyoarya"],
	["make", "funny faces at me", "Poyoarya"],
	["remind", "me of my ex", "Poyoarya"],
	["make", "me SD", "Poyoarya"],
	["violate", "the rules", "Poyoarya"],
	["totally spook", "me out", "Poyoarya"],
	["run", "a company for 16 hours a day", "Poyoarya"],
	["make", "excuses", "Poyoarya"],
	["speak", "Japanese", "Poyoarya"],
	["use", "glitches", "Poyoarya"],
	["use", "better moves than me", "Poyoarya"],
	["use", "motion controls", "Poyoarya"],
	["sit", "slightly closer to the screen", "Poyoarya"],
	["do not wear", "glasses", "Poyoarya"],
	["use", "items", "Poyoarya"],
	["do not let", "me grab him", "Poyoarya"],
	["spam", "projectiles", "Poyoarya"],
	["shield", "too much", "Poyoarya"],
	["air dodge", "all the time", "Poyoarya"],
	["roll", "", "Poyoarya"],
	["pause", "mid-match", "Poyoarya"],
	["save", "replays", "Poyoarya"],
	["pick", "stages that I don't like", "Poyoarya"],
	["block", "the screen", "Poyoarya"],
	["use", "an ugly alternative costume", "Poyoarya"],
	["use", "counters too much", "Poyoarya"],
	["only use", "the A button", "Poyoarya"],
	["only use", "the B button", "Poyoarya"],
	["spam", "PK Fire", "Poyoarya"],
	["do not go", "to the doctor", "Poyoarya"],

	["only go","for footstools", "Alpharad"],
	["threaten", "me", 'wsbc'],
	["mangle", "my hand", 'wsbc'],
	["crash", "", 'notamacuser'],
	["fart", "on the bike", 'notamacuser'],
	["betray", "me", 'Tommy Wiseau'],
	["hurt", ":-(", "wsbc"],
	["make", "me cry", 'Copilot'],
	["fuck", "my mom", 'Copilot'],
	["fuck", "my wife", 'Eggman'],
	["misfire", "all the goddamn time", 'Luigi'],
];
