/**people that we make fun of*/
export const noun: Noun[] = [
	["My eyes", "3p", "niffyjiffy"],
	["The TV", "3s", "niffyjiffy"],
	["This setup", "3s", "Taerk"],
	["My controller", "3s", "Taerk"],
	["I", "1s", "niffyjiffy"],
	["The camera", "3s", "Dr Deletus"],
	["Your character", "3s", "/u/KindaFunnyUsername"],
	["My chair", "3s", "/u/shadowpikachu"],
	["The lag", "3s", "/u/DrankeyKrang"],
	["My skills", "3p", "/u/DrankeyKrang"],
	["My phone", "3s", "/u/DrankeyKrang"],
	["My nose", "3s", "/u/DrankeyKrang"],
	["The control stick", "3s", "/u/p0rtugalvii"],
	["The venue", "3s", "/u/p0rtugalvii"],
	["The stage", "3s", "/u/DeadLineClock"],
	["The bracket", "3s", "/u/DeadLineClock"],
	["The matchup", "3s", "/u/DeadLineClock"],

	["You", "2s", "Taerk"],
	["My son", "3s", "niffyjiffy"],
	["This game", "3s", "Taerk"],
	["My hands", "3p", "niffyjiffy"],
	["My fingers", "3p", "niffyjiffy"],
	["Your main", "3s", "/u/KindaFunnyUsername"],
	["My butt", "3s", "/u/shadowpikachu"],
	["My fingernails", "3p", "/u/DrankeyKrang"],
	["My breakfast", "3s", "/u/deluxejoe"],
	["Randall", "3s", "/u/NormalNavi"],
	["My 3DS", "3s", "/u/NormalNavi"],
	["Your 3DS", "3s", "/u/NormalNavi"],
	["Smash 64", "3s", "Taerk"],
	["Melee", "3s", "Taerk"],
	["Brawl", "3s", "Taerk"],
	["Smash 4", "3s", "Taerk"],
	["Netplay", "3s", "Taerk"],
	["My drink", "3s", "Taerk"],
	["Your amiibo", "3s", "/u/Meester_Tweester"],
	["My fedora", "3s", "/u/PhoenixBurning"],
	["Mango", "3s", "/u/DeadLineClock"],
	["My ride home", "3s", "/u/DeadLineClock"],

	["My dog", "3s", "/u/DeadLineClock"],
	["Your mom", "3s", "Taerk"],
	["The spectators", "3p", "Taerk"],
	["The commentators", "3p", "Taerk"],
	["Everyone", "3s", "Taerk"],
	["The desire sensor", "3s", "Taerk"],
	["Sakurai", "3s", "Taerk"],
	["The Vernal Equinox", "3s", "/u/RoflPost"],
	["/r/smashbros", "3s", "/u/NormalNavi"],
	["SmashBoards", "3s", "/u/NormalNavi"],
	["RNGesus", "3s", "/u/NormalNavi"],
	["My Zapper", "3s", "/u/NormalNavi"],
	["The John generator", "3s", "/u/NormalNavi"],
	["My waifu", "3s", "/u/radicalhighway_"],
	["The sponsors", "3p", "/u/radicalhighway_"],
	["Nintendo", "3s", "/u/radicalhighway_"],
	["Twitch", "3s", "/u/radicalhighway_"],
	["Gimr", "3s", "/u/radicalhighway_"],
	["Mr. Game &amp; Watch", "3s", "/u/radicalhighway_"],
	["Prog", "3s", "/u/radicalhighway_"],
	["Doritos", "3p", "/u/radicalhighway_"],
	["Le toucan", "3s", "/u/PhoenixBurning"],
	["My ride home", "3s", "/u/DeadLineClock"],
	["The salt shaker", "3s", "/u/DeadLineClock"],
	["The matchup", "3s", "/u/DeadLineClock"],
	["The stock market", "3s", "/u/DeadLineClock"],
	["GRsmash", "3s", "/u/DeadLineClock"],
	["My panties", "3p", "/u/DeadLineClock"],
	["The left joycon", "3s", "/u/supaPILLOT"],

	["My controller", "3s", "Poyoarya"],
	["The sun", "3s", "Poyoarya"],
	["My hands", "3p", "Poyoarya"],
	["Everyone", "3s", "Poyoarya"],
	["The TV", "3s", "Poyoarya"],
	["The crowd", "3s", "Poyoarya"],
	["My opponent", "3s", "Poyoarya"],
	["My chair", "3s", "Poyoarya"],
	["His controller", "3s", "Poyoarya"],
	["Meta Knight", "3s", "Poyoarya"],
	["Roy's wavedash", "3s", "Poyoarya"],
	["My mother", "3s", "Poyoarya"],
	["My brain", "3s", "Poyoarya"],
	["My 3DS", "3s", "Poyoarya"],
	["Nintendo", "3s", "Poyoarya"],
	["My Twitter followers", "3p", "Poyoarya"],
	["My eyes", "3p", "Poyoarya"],
	["The DLC", "3s", "Poyoarya"],
	["The commentators", "3p", "Poyoarya"],
	["The music", "3s", "Poyoarya"],
	["Final Destination", "3s", "Poyoarya"],
	["Reggie Fils-Aim&eacute;", "3s", "Poyoarya"],
	["The venue", "3s", "Poyoarya"],
	["My skills", "3p", "Poyoarya"],
	["The stream", "3s", "Poyoarya"],
	["Sakurai", "3s", "Poyoarya"],
	["The ledge", "3s", "Poyoarya"],
	["My foot", "3s", "Poyoarya"],
	["The C-stick", "3s", "Poyoarya"],
	["Project M", "3s", "Poyoarya"],
	["Your shoes", "3p", "Poyoarya"],
	["My mother's basement", "3s", "Poyoarya"],
	["The USA", "3s", "Poyoarya"],
	["Tap jump", "3s", "Poyoarya"],
	["Jigglypuff", "3s", "Poyoarya"],
	["I", "1s", "Poyoarya"],
	["PAC-MAN", "3s", "Poyoarya"],
	["Cloud Strife", "3s", "Poyoarya"],
	["My scarf", "3s", "Poyoarya"],
	["The T.O.", "3s", "Poyoarya"],
	["EVO", "3s", "Poyoarya"],
	["Leffen", "3s", "Poyoarya"],

	["Smash Ultimate", "3s", "wsbc"],
	["My Uber driver", "3s", "wsbc"],
	["My wife", "3s", "wsbc"],
	["My dick", "3s", "wsbc"],
	["My tummy", "3s", "wsbc"],
	["Hungrybox", "3s", "wsbc"],
	["Miiverse", "3s", "wsbc"],
	["This Man", "3s", "notamacuser"],
	["The Wii U", "3s", "wsbc"],
	["Donkey Kong", "3s", "wsbc"],
	["Captain Falcon", "3s", "wsbc"],
	["My game", "3s", "notamacuser"],
	["My sponsor", "3s", "wsbc"],
	["Chat", "3s", "wsbc"],
	["Alpharad", "3s", "notamacuser"],
	["For Glory", "3s", "notamacuser"],
	["The wifi here", "3s", "wsbc"],
	["Wii Fit Trainer", "3s", "notamacuser"],
	["Falco", "3s", "wsbc"],
	["Someone", "3s", "Walter White"],
	["That", "3s", "wsbc"],
	["This", "3s", "wsbc"],
	["Those", "3p", "wsbc"],
	["Mr. President", "3s", "wsbc"],
	["The Voices", "3p", "wsbc"],
];
