export const verbInt: VerbInt[] = [
	["counter-picked the stage", "Taerk"],
	["counter-picked the character", "Taerk"],
	["self-destructed", "Taerk"],
	["[hack]", "Taerk"],
	["[cheat]", "Taerk"],
	["[listen] to the wrong song", "Taerk"],
	["[mess] with the setup", "Taerk"],
	["[use] the wrong tag", "Taerk"],
	["[lose] on purpose", "Taerk"],
	["[use] rumble", "Taerk"],
	["teamed up on me", "Taerk"],
	["just switched games", "Taerk"],

	["[kill] me", "/u/Mitsjol"],
	["[make] me sleepy", "/u/RoflPost"],
	["[use] illegal tactics", "/u/DrankeyKrang"],
	["[use] banned characters", "/u/DrankeyKrang"],
	["[use] glitches", "/u/DrankeyKrang"],
	["only plays to win", "/u/DrankeyKrang"],
	["[explode]", "/u/Her0_0f_time"],
	["[slip]", "/u/ProjectMFeeni-ngNigga"],
	["[stare] at me", "/u/2m2m_NoClown"],
	["[stare] at you", "/u/2m2m_NoClown"],
	["[nudge] my R-cancelling knee", "/u/Erotaku12943"],
	["[have] a heart attack", "/u/KiJoBu"],
	["[use] gimmicky custom moves", "/u/DrankeyKrang"],
	["[throw] something at me", "/u/DeadLineClock"],
	["[call] me names", "/u/DeadLineClock"],
	["[get] too much sleep", "/u/Her0_0f_time"],
	["[murder] the commentator", "/u/DeadLineClock"],
	["[tell] me it would work", "/u/NormalNavi"],
	["[save] you", "/u/Mitsjol"],
	["[want] to make a gfycat", "/u/Her0_0f_time"],
	["[mess] up my L-cancels", "/u/Erotaku12943"],
	["[call] me", "/u/Mitsjol"],
	["[steal] my main", "/u/404House"],

	["johns too much", "/u/Slyphoria"],
	["did 9/11", "/u/DeadLineClock"],
	["should have teched that", "/u/DeadLineClock"],
	["got no goddamn characters", "/u/KiJoBu"],
	["ragequit", "/u/DeadLineClock"],
	["ran out of jumps", "/u/Meester_Tweester"],
	["nudged me", "/u/Erotaku12943"],
	["messed up my Z-cancels", "/u/Erotaku12943"],
	["share-stocked me", "/u/DeadLineClock"],
	["didn't give me my money back", "/u/DeadLineClock"],
	["didn't get Scar and Toph to commentate", "/u/Her0_0f_time"],
	["broke the John generator", "/u/Her0_0f_time"],
	["started watching Shrek", "/u/Her0_0f_time"],
	["spams", "/u/KindaFunnyUsername"],

	["[walk] in front of the screen", "Poyoarya"],
	["[tangle] my controller cable", "Poyoarya"],
	["[sleep]", "Poyoarya"],
	["[taunt]", "Poyoarya"],
	["[cheat]", "Poyoarya"],
	["[make] funny faces at me", "Poyoarya"],
	["[be] trash-talking mid-match", "Poyoarya"],
	["[remind] me of my ex", "Poyoarya"],
	["[make] me SD", "Poyoarya"],
	["[violate] the rules", "Poyoarya"],
	["totally [spook] me out", "Poyoarya"],
	["[run] a company for 16 hours a day", "Poyoarya"],
	["[make] excuses", "Poyoarya"],
	["spammed projectiles", "Poyoarya"],
	["[speak] Japanese", "Poyoarya"],
	["[use] glitches", "Poyoarya"],
	["[use] better moves than me", "Poyoarya"],
	["[use] motion controls", "Poyoarya"],
	["[sit] slightly closer to the screen", "Poyoarya"],
	["[do] not wear glasses", "Poyoarya"],
	["[use] items", "Poyoarya"],
	["[do] not let me grab him", "Poyoarya"],
	["shielded too much", "Poyoarya"],
	["air dodged", "Poyoarya"],
	["[roll]", "Poyoarya"],
	["[pause] mid-match", "Poyoarya"],
	["[save] replays", "Poyoarya"],
	["only uses the A button", "Poyoarya"],
	["only used the B button", "Poyoarya"],
	["[pick] stages that I don't like", "Poyoarya"],
	["[block] the screen", "Poyoarya"],
	["[use] an ugly alternative costume", "Poyoarya"],
	["[use] counters too much", "Poyoarya"],
	["spams PK Fire", "Poyoarya"],
	["[not go] to the doctor", "Poyoarya"],

	["only goes for footstools", "Alpharad"],
	["[threaten] me", 'wsbc'],
	["[mangle] my hand", 'wsbc'],
	["TURNED HER AGAINST ME", "Anakin Skywalker"],
	["ain't Falco", "wsbc"],
	["cooked here", "Walter White"],
	["died of ligma", "Steve Jobs"],
	["hurts :-(", "wsbc"],
	["posted my nudes on twitter.com", "Eggman"],
	["killed my father", 'Inigo Montoya'],
	["ate my son", 'Ted Cruz'],
	["[crash]", 'notamacuser'],
	["[fart] on the bike", 'notamacuser'],
	["[betray] me", 'Tommy Wiseau'],
];
