# development
<IfModule !mod_ssl.c>
<VirtualHost *:80>
  ServerName localhost
  Include "/httpd/waluigi_servebeer/vhost/wsbc_main.conf"
</VirtualHost>
</IfModule>

# deployment
<IfModule mod_ssl.c>
# HTTP redirect
<VirtualHost *:80>
  ServerName waluigi-servebeer.com
  RewriteEngine on
  RewriteCond %{SERVER_NAME} =waluigi-servebeer.com
  RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

# HTTPS config
<VirtualHost *:443>
  ServerName waluigi-servebeer.com
  
  Include "/httpd/waluigi_servebeer/vhost/wsbc_main.conf"

  # LetsEncrypt
  SSLCertificateFile /etc/letsencrypt/live/waluigi-servebeer.com/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/waluigi-servebeer.com/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>

Include "/httpd/online/vhost/ip_response.conf"
Include "/httpd/online/vhost/livekit.conf"

</IfModule>
